use super::IssueExplanation;

pub(super) const MISC_ISSUES: &[IssueExplanation] = &[
    issue!(
        "feature-flag",
        "dart-decimate/feature-flag",
        &["feature-flag", "feature-flags", "flags"],
        "Feature flag",
        "A Dart or Flutter feature flag pattern was detected.",
        "Flag inventories help find stale rollout logic and risky config gates.",
        "bool.fromEnvironment('NEW_FLOW') gates production behavior.",
        "Review owner, rollout state, and dead-code traces before deleting flag branches.",
        next_line_suppressions!("feature-flag"),
        &["dart-decimate flags --format json"],
    ),
    issue!(
        "security-candidate",
        "dart-decimate/security-candidate",
        &[
            "security",
            "security-candidate",
            "security-candidates",
            "security-sink",
            "hardcoded-secret",
            "firebase-api-key",
            "insecure-transport",
            "tls-bypass",
            "webview-risk",
            "process-execution",
            "process-exec",
            "raw-sql",
            "plain-secret-storage",
            "weak-randomness",
        ],
        "Security candidate",
        "A deterministic local security review candidate was detected.",
        "Dart Decimate surfaces candidates for agent verification; it does not prove exploitability.",
        "HttpClient.badCertificateCallback or an http:// URL appears in reachable code.",
        "Verify source, sink, reachability, and product intent before changing code.",
        next_line_suppressions!("security-sink"),
        &["dart-decimate security --format json --surface"],
    ),
    issue!(
        "stale-suppression",
        "dart-decimate/stale-suppression",
        &[
            "stale-suppression",
            "stale-suppressions",
            "unused-suppression",
            "unused-suppressions"
        ],
        "Stale suppression",
        "A Dart Decimate or Fallow inline suppression no longer suppresses any finding.",
        "Stale suppressions hide historical context and can mask future findings accidentally.",
        "// dart-decimate-ignore-next-line unused-export remains above live code with no finding.",
        "Remove the unused suppression comment.",
        &[],
        &["dart-decimate check --format json"],
    ),
    issue!(
        "missing-suppression-reason",
        "dart-decimate/missing-suppression-reason",
        &["missing-suppression-reason", "missing-suppression-reasons"],
        "Missing suppression reason",
        "A Dart Decimate or Fallow inline suppression is missing required justification text.",
        "Reasoned suppressions make intentional exceptions reviewable and prevent silent cleanup drift.",
        "// dart-decimate-ignore-next-line unused-export omits why the export is intentionally kept.",
        "Add a short reason after `--`, `because`, or `reason:`.",
        &[],
        &["dart-decimate check --format json"],
    ),
];
